services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Replace_me
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Replace_me
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes:
  pgdata:
  mongodata:
