services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Replace_me
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
